name: Update frontmatter for story archetype

on:
  pull_request:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    embed-frontmatter:
      runs-on: ubuntu-latest
      steps:
        - name: Markdown Embed Code From File
          uses: tokusumi/markdown-embed-code@v1.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            markdown: "add-a-story.md"
            message: "Updating embedded frontmatter in story instructions"
            no_change: "No changes to story instructions"
